import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
=======
import { Inter } from "next/font/google";
>>>>>>> 1fea9648068850d424b546b10396a80a83095cc6
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Disaster Management Platform | SIH25008",
  description: "A comprehensive disaster management platform for students and teachers",
>>>>>>> 1fea9648068850d424b546b10396a80a83095cc6
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        
        <main className="fade-in slide-up">
          {children}
        </main>
        
        <footer className="bg-gray-800 text-white py-8 mt-">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div>
                <h3 className="text-lg font-semibold mb-4">Disaster Management</h3>
                <p className="text-gray-400">A comprehensive platform for disaster management education and training.</p>
              </div>
              <div>
                <h3 className="text-lg font-semibold mb-4">Quick Links</h3>
                <ul className="space-y-2">
                  <li><a href="/" className="text-gray-400 hover:text-white transition-colors">Home</a></li>
                  <li><a href="/login" className="text-gray-400 hover:text-white transition-colors">Login</a></li>
                  <li><a href="/register" className="text-gray-400 hover:text-white transition-colors">Register</a></li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold mb-4">Contact</h3>
                <p className="text-gray-400">Email: info@disastermanagement.edu</p>
                <p className="text-gray-400">Phone: +91 123-456-7890</p>
              </div>
            </div>
            <div className="border-t border-gray-700 mt-8 pt-6 text-center text-gray-400">
              <p>&copy; {new Date().getFullYear()} Disaster Management Platform. All rights reserved.</p>
            </div>
          </div>
        </footer>
>>>>>>> 1fea9648068850d424b546b10396a80a83095cc6
      </body>
    </html>
  );
}
